package test.view.slidealphapostion;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.createTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updateTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productName
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productCode
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productSku
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productSku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productStatus
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.categoryId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private Byte categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productBrand
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productBrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.adminId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private Integer adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productDesc
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productUrl
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.productUnit
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	private String productUnit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	
	
	private String  firstLetter;
	
	
	
	
	public String getFirstLetter() {
		return firstLetter;
	}

	public void setFirstLetter(String firstLetter) {
		this.firstLetter = firstLetter;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.createTime
	 * @return  the value of product.createTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.createTime
	 * @param createTime  the value for product.createTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updateTime
	 * @return  the value of product.updateTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updateTime
	 * @param updateTime  the value for product.updateTime
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productName
	 * @return  the value of product.productName
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productName
	 * @param productName  the value for product.productName
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productCode
	 * @return  the value of product.productCode
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productCode
	 * @param productCode  the value for product.productCode
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode == null ? null : productCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productSku
	 * @return  the value of product.productSku
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductSku() {
		return productSku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productSku
	 * @param productSku  the value for product.productSku
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductSku(String productSku) {
		this.productSku = productSku == null ? null : productSku.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productStatus
	 * @return  the value of product.productStatus
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductStatus() {
		return productStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productStatus
	 * @param productStatus  the value for product.productStatus
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductStatus(String productStatus) {
		this.productStatus = productStatus == null ? null : productStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.categoryId
	 * @return  the value of product.categoryId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public Byte getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.categoryId
	 * @param categoryId  the value for product.categoryId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setCategoryId(Byte categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productBrand
	 * @return  the value of product.productBrand
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductBrand() {
		return productBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productBrand
	 * @param productBrand  the value for product.productBrand
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductBrand(String productBrand) {
		this.productBrand = productBrand == null ? null : productBrand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.adminId
	 * @return  the value of product.adminId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.adminId
	 * @param adminId  the value for product.adminId
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productDesc
	 * @return  the value of product.productDesc
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductDesc() {
		return productDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productDesc
	 * @param productDesc  the value for product.productDesc
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc == null ? null : productDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productUrl
	 * @return  the value of product.productUrl
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductUrl() {
		return productUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productUrl
	 * @param productUrl  the value for product.productUrl
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl == null ? null : productUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.productUnit
	 * @return  the value of product.productUnit
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public String getProductUnit() {
		return productUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.productUnit
	 * @param productUnit  the value for product.productUnit
	 * @mbggenerated  Mon Apr 21 20:34:58 CST 2014
	 */
	public void setProductUnit(String productUnit) {
		this.productUnit = productUnit == null ? null : productUnit.trim();
	}
}